name: "tasktracker"

networks:
  main:
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasktracker
    volumes:
      - ./.docker/database:/var/lib/postgresql/data
    networks:
      - main
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  migrate:
    container_name: migrations
    image: migrate/migrate
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"
    volumes:
      - ./migrations:/migrations
    command: >
      -source file:///migrations 
      -database postgres://postgres:postgres@postgres:5432/tasktracker?sslmode=disable 
      up
    networks:
      - main

  app:
    container_name: tasktracker
    build:
      context: .
      dockerfile: docker/task/Dockerfile
    restart: always
    depends_on:
      migrate:
        condition: service_completed_successfully
    networks:
      - main
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env

  auth:
    container_name: auth
    build:
      context: .
      dockerfile: docker/auth/Dockerfile
    restart: always
    depends_on:
      migrate:
        condition: service_completed_successfully
    networks:
      - main
    env_file:
      - .env
