name: Go

on: 
    push:
        branches:
            - '*'
        paths:
            - '**.go'
            - 'go.mod'
            - 'go.sum'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                go-version: 'latest'

            - name: Build
              run: |
                go mod tidy
                go build -v ./...


            - name: Lint
              uses: golangci/golangci-lint-action@v4
              with:
                version: latest

            - name: Test
              run: |
                go mod tidy
                go test -v -race ./...